version: '2.1'
services:
  Router:
    build: ./Router
    privileged: true
    depends_on:
      - RabbitMQ 
  SpotifyClient:
    build: ./SpotifyClient
    privileged: true
  Power:
    build: ./Power
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ
  RabbitMQ:
    build: ./RabbitMQ
    network_mode: "host"
    privileged: true
