version: '2.1'
services:
  # SensorDataSend:
  #   build: ./SensorDataSend
  #   network_mode: "host"
  #   privileged: true
  duHToIoTHub:
    build: ./duHToIoTHub
    privileged: true
    depends_on:
      - RabbitMQ 
  SpotifyClient:
    build: ./SpotifyClient
    privileged: true
  # SensorDataGet:
  #   build: ./SensorDataGet
  #   depends_on:
  #     - SensorDataSend
  #   privileged: true
  PowerWrite:
    build: ./PowerWrite
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ
      - PowerRead 
  PowerRead:
    build: ./PowerRead
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ 
  RabbitMQ:
    build: ./RabbitMQ
    network_mode: "host"
    privileged: true
