version: '2.1'
services:
  Router:
    build: ./Router
    privileged: true
    network_mode: "host"
    expose: 
      - "5672"
    depends_on:
      - RabbitMQ 
  Power:
    build: ./Power
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ
  RabbitMQ:
    build: ./RabbitMQ
    network_mode: "host"
    privileged: true
