version: '2.1'
services:
  SensorDataSend:
    build: ./SensorDataSend
    network_mode: "host"
    privileged: true
  duHToIoTHub:
    build: ./duHToIoTHub
    privileged: true
    restart: always
  SpotifyClient:
    build: ./SpotifyClient
    restart: always
    privileged: true
  SensorDataGet:
    build: ./SensorDataGet
    depends_on:
      - SensorDataSend
    privileged: true
  PowerWrite:
    build: ./PowerWrite
    restart: always
    privileged: true
  PowerRead:
    build: ./PowerRead
    restart: always
    privileged: true    
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
    cap_add: 
      - SYS_RAWIO
  RabbitMQ:
    build: ./RabbitMQ
    network_mode: "host"
    privileged: true    
